[features]
seeds = false
skip-lint = false

[programs.localnet]
sealed_skill = "APpCcBAPBAn92mz8KLv3RgFTqLKHMyMAvepudiUpNb6s"

[programs.devnet]
sealed_skill = "APpCcBAPBAn92mz8KLv3RgFTqLKHMyMAvepudiUpNb6s"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec tsx tests/sealed-skill.ts"
